version: "3.8"

services:
    mysql-service:
        container_name: mysql-service
        image: mysql:8.0
        hostname: mysql-service
        networks: 
            - atm-web-network
        environment:
          - MYSQL_ROOT_PASSWORD=Sirikon190843
          - MYSQL_USER=root
          - MYSQL_PASSWORD=Sirikon190843
        ports:
            - 3307:3306
        cap_add:
            - SYS_NICE
        volumes: 
            - web_db:/var/lib/mysql

    bankaccount-api:
        container_name: bankaccount-api
        networks: 
            - atm-web-network
        restart: on-failure
        build:
            context: ./bankaccount-api
            dockerfile: Dockerfile
        depends_on:
            - mysql-service
        ports:
            - 8091:8091
    
    atm-web:
        container_name: atm-web
        networks: 
            - atm-web-network
        restart: on-failure
        build:
            context: ./atm-web
            dockerfile: Dockerfile
        ports:
            - 8090:8090
        depends_on:
            - mysql-service
            - bankaccount-api

networks:
    atm-web-network:
        driver: bridge

volumes:
    web_db: